### PR TITLE
Update the activation of "Local Mode"

### PR DESCRIPTION
**Pull request by tmh-grunwald-markus**
This PR fixes https://github.com/balena-io/balena-cli-masterclass/issues/42 by updating the README.md file with current values.

### CODE REVIEW

**Review by floion — APPROVED** [review]

**Review by vipulgupta2048 — APPROVED** [review]

**Comment by vipulgupta2048** [comment]
@tmh-grunwald-markus Thanks for opening the PR, you seem to have missed the commit prefix to signify the change type for your PR. Please check our [Contributing guide](https://github.com/balena-io/docs/blob/master/CONTRIBUTING.md#creating-commits-in-line-with-semantic-versioning) to add a `patch` Change-type to your commit.

**Comment by tmh-grunwald-markus** [comment]
> Please [...] add a `patch` Change-type to your commit.

Done :)

**Comment by floion** [comment]
> > Please [...] add a `patch` Change-type to your commit.
> 
> Done :)

Can't see it unfortunately. Can you double check please?

**Comment by acostach** [comment]
Hi @tmh-grunwald-markus the change type still does not appear to be pushed.

Can you please try to do a git commit --amend

then modify the commit message from:

```
Update the activation of "Local Mode" 
```

to

```
Update the activation of "Local Mode" 

Change-type: patch
Signed-off-by: Your Name <your@email.com>
```

once completed, rebase you branch on top of master to bring in latest merged changes and then force push your branch.

**Comment by vipulgupta2048** [comment]
Your commits seem to have made changes to a past release. Can you squash and cleanup the reset of the commits. This commit of your should work [e32a665](https://github.com/balena-io/balena-cli-masterclass/pull/43/commits/e32a6657d369da4b970cff53635199c3dea7ddef), this commit should work. The rest can be cleaned up.

**Pull request closed without merging**
